### ISSUE TITLE
Marker icons?

### ISSUE THREAD

**Issue by ethanclevenger91** [GuillaumeLeclerc/vue-google-maps#28] opened 2016-03-04 23:32 UTC
Just wanted to double-check the functionality of this/how it works. Right now I've got:

```markers: [{
      position: {lat: 41.585095, lng: -93.624523},
      ifw:false,
      content:'',
      icon: {
        path: google.maps.SymbolPath.CIRCLE
      }
    }]```

The marker shows up on the map if I leave off the icon argument, but when I include it, I get `google is not defined`. I've also tried using https://github.com/ethanclevenger91/fontawesome-markers, which has worked for me in the past using the vanilla maps library, so it ends up looking like this:

```path: fontawesome.markers.EXCLAMATION_CIRCLE```

And in that case, I just get the regular old icon. Any advice on this?

**Comment by ethanclevenger91** [comment] 2016-03-04 23:34
See here for predefined symbols documentation: https://developers.google.com/maps/documentation/javascript/examples/marker-symbol-predefined

**Comment by ethanclevenger91** [comment] 2016-03-05 00:02
Moved this after the `loaded` promise as follows (sorry I'm not using a bundler):

```VueGoogleMap.loaded.then(function() {
      this.markers[0].icon.path = google.maps.SymbolPath.CIRCLE;
    }.bind(this))```

If I log `google.maps.SymbolPath` here I see the various constants, but the marker remains the same.

**Comment by GuillaumeLeclerc** [comment] 2016-03-05 10:06
I haven't tested custom path, only png's with this feature. Do you have a fiddle so I can try to debug it ?

Thank you for your feedback !

**Comment by GuillaumeLeclerc** [comment] 2016-03-24 13:24
Do you have news about this or is it fine ?

**Comment by GuillaumeLeclerc** [comment] 2016-03-27 17:56
I'll close it because of inactivity. Feel free to reopen it if you still have a problem

**Comment by FWSimon** [comment] 2016-04-08 12:01
I still have this error :-1: have no idea how to set a custom icon

**Comment by GuillaumeLeclerc** [comment] 2016-04-08 12:19
I will try to reproduce myself then

**Comment by FWSimon** [comment] 2016-04-08 12:37
Right now i have this


````
    data: function () {
        return {
            // icon:  { icon: './images/icons/map/center.png' },
            map   : {
                center : {},
                mapType: 'terrain'
            },
            markers: [{
                icon: { path: 'https://www.google.dk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png' }
            }],
            OpeningHours: []
        };
    },
````

Then i push some markers into the `markers` object with this
````
this.markers.push(
                        {
                            position: { lat: parseFloat(markerData.geo_lat), lng: parseFloat(markerData.geo_lng) },
                            centerWebname: markerData.webname,
                            slug: markerData.slug,
                            icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png',
                            id: markerData.id //Is used to grab the Opening hours data.
                        }
                    );
````


in my view i try this
```
 <marker
                    @g-click="FetchOpeningHours(m.id)"
                    v-if="markers"
                    :icon.sync="m.icon"
                    :position.sync="m.position" v-for="m in markers">
````

but vue keep saying `[Vue warn]: Invalid prop: type check failed for icon="m.icon". Expected Object, got String.`

**Comment by ethanclevenger91** [comment] 2016-04-08 13:13
Sorry I went dark on this! I haven't had time to do up a fiddle but will
update if I do get an opportunity.

**Comment by FWSimon** [comment] 2016-04-10 09:54
Thanks @ethanclevenger91 I'm really stuck with the icons

**Comment by GuillaumeLeclerc** [comment] 2016-04-10 09:55
I've allocated some time Wednesday to work on this. If I don't update it just ping me.

**Comment by ridnarong** [comment] 2016-04-11 06:47
Finally I got it. you just set icon prop to `icon: { url: '/path/to/icon.png' }` For more options please check https://developers.google.com/maps/documentation/javascript/markers#complex_icons 

I this this cause by change in Google Map API previously it used Icon object to set icon appearance So he require this prop to object. Now you can just use string path of your icon image.

I think, this issue may don't need to be fixed only provide an example of setting icon will be ok. ^_^

**Comment by FWSimon** [comment] 2016-04-11 06:54
oh gonna try that @ridnarong ! Good job

**Comment by FWSimon** [comment] 2016-04-11 07:38
@ridnarong can i see your data: function?

should the icon be in the markers object?

```
  data: function () {
        return {
            icon: { url: './images/icons/map/center.png' },
            map   : {
                center : {},
                mapType: 'terrain'
            },
            markers: [{
                icon: { path: 'https://www.google.dk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png' }
            }],
            OpeningHours: []
        };
```

**Comment by ridnarong** [comment] 2016-04-11 08:03
```javascript
  data () {
    let markers = []
    for (let feed_id in this.stations) {
      markers.push({
        name: this.stations[feed_id].name,
        position: {lat: this.stations[feed_id].lat, lng: this.stations[feed_id].lon},
        isClicked: false,
        icon: {url:  '/static/darkgreen_MarkerS.png'}
      })
    }
    return {
      mapCenter: {lat: 14.0774503, lng: 100.6014391},
      mapZoom: 17,
      markers: markers,
      selectedMarker: 0
    }
```

**Comment by FWSimon** [comment] 2016-04-11 08:14
@ridnarong I have tried this


```
   this.markers.push(
                        {
                            position: { lat: parseFloat(markerData.geo_lat), lng: parseFloat(markerData.geo_lng) },
                            centerWebname: markerData.webname,
                            slug: markerData.slug,
                            icon: {url: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
                            id: markerData.id //Is used to grab the Opening hours data.
                        }
                    );
```


and then my data is this

```
    data: function () {
        return {
            map   : {
                center : {},
                mapType: 'terrain'
            },
            markers: [{
                // icon: { url: './images/icons/map/center.png' }
            }],
            OpeningHours: []
        };
    },```

But still not working :(
Do i need to set something in my view?

**Comment by ridnarong** [comment] 2016-04-11 08:53
Here is my view:
```html
<template>
  <div class="rows">
    <div class="col-md-12">
      <map :center.sync="mapCenter"
        :zoom.sync="mapZoom", >
        <marker
          v-for="m in markers"
          :position.sync="m.position"
          :icon.sync="m.icon"
          @g-click="handleClickMarker($index)">
            <info-window
            :opened.sync="m.isClicked">
            {{m.name}}
            </info-window>
        </marker>
      </map>
    </div>
  </div>

</template>
```

**Comment by FWSimon** [comment] 2016-04-11 09:21
Yay now it worked! 👍 Thanks

**Comment by GuillaumeLeclerc** [comment] 2016-04-11 09:29
Could you add something about it in the wiki. It would be cool for other users I think

**Comment by FWSimon** [comment] 2016-04-11 09:41
@GuillaumeLeclerc Sure! :)

**Comment by FWSimon** [comment] 2016-04-11 09:46
FYI and other people in the future there is some docs here

https://github.com/GuillaumeLeclerc/vue-google-maps/wiki/Marker#setup-custom-icon-for-the-markers

**Comment by ethanclevenger91** [comment] 2016-04-11 13:28
So my issue is with SVG paths. Working on a fiddle now, so don't close just yet ;)

**Comment by ethanclevenger91** [comment] 2016-04-11 13:33
So for some reason I can't get this jsFiddle to function. Running into a JS error in vue-google-maps.js. Care to take a look?
https://jsfiddle.net/thxeg5Ls/

**Comment by GuillaumeLeclerc** [comment] 2016-04-11 13:42
@FWSimon I'm sorry but I haven't read your messages but I thought you were solving the SVG issue. There are no issues with normal icons. What you added in the wiki is just "how to pass a parameter to a component in vue" and is true for every other attributes I don't think it deserve an entry in the wiki it's just basically "how to use vue" and does not fit here in my opinion. 

Moreover you can even make it work without using the data object by doing something like this.

`<marker :icon="{url: '/your/url'}"></marker>`

If your marker is always the same (which is '/your/url' in your entry in the wiki) you should not use `data` because here it's not data but a constant instead. Your advice is therefore bad practice in my opinion.

If you don't see any problem with this I'll probably remove this part of the wiki since it's more misleading than informative

**Comment by FWSimon** [comment] 2016-04-11 13:49
ah, your right @GuillaumeLeclerc it was a simple .png icon I wanted to set. but yea I had no idea where to put it in my JS.

I don't put it in my view because it's a marker that change / is not the same every time.

It's okay to delete the wiki :)

**Comment by GuillaumeLeclerc** [comment] 2016-04-11 13:57
So you have a marker for every icon. If there are only few possible values I advise you to use a map from a key to the actual url. and only store the key inside your marker.

**Comment by ethanclevenger91** [comment] 2016-04-11 14:08
@GuillaumeLeclerc re: SVGs, I _did_ post a fiddle, but I'm getting a bug in the vue-google-maps source. If you could take a look, it'd be appreciated, and then I can set it up to use an SVG path and demonstrate that bug.

https://jsfiddle.net/thxeg5Ls/

**Comment by GuillaumeLeclerc** [comment] 2016-04-11 20:19
I will do on Wednesday, maybe even tomorrow If I can find the time. Thank you for your fiddle

**Comment by GuillaumeLeclerc** [comment] 2016-04-11 20:19
Sorry If I closed the issue I think I clicked the wrong button. Didn't even noticed that.

**Comment by ethanclevenger91** [comment] 2016-04-11 20:54
Perfect, thanks!

**Comment by GuillaumeLeclerc** [comment] 2016-04-13 20:15
Your fiddle does not work because as stated in the README if you don't use and packer then you need to include lodash as a dependency. Moreover even if I fix this your fiddle does not use any custom icons. It's quite complicated to help you here.

**Comment by ethanclevenger91** [comment] 2016-04-13 20:59
Sorted out. Now that it's functioning, I feel comfortable tossing in the custom path. I used the data example from above with the SVG's path information. The custom path is ignored: https://jsfiddle.net/thxeg5Ls/2/

Here's the documentation on using both w/ the vanilla JS API: https://developers.google.com/maps/documentation/javascript/symbols#add_to_marker

**Comment by GuillaumeLeclerc** [comment] 2016-04-13 21:46
I almost went crazy with this bug ;) 

:icon should be on marker not on the map... 

I moved it to marker and it worked

**Comment by GuillaumeLeclerc** [comment] 2016-04-13 21:47
[fixed fiddle](https://jsfiddle.net/ux4d3hbj/)

**Closed by GuillaumeLeclerc** 2016-04-13 21:46 UTC

**Comment by FWSimon** [comment] 2016-04-14 08:27
wow good job @GuillaumeLeclerc !

**Comment by mastershaig** [comment] 2016-08-18 11:36
Thanks, it helped @GuillaumeLeclerc !

**Comment by davodaslanifakor** [comment] 2017-05-23 06:33
@GuillaumeLeclerc 
hi i have something problem 
this is my cod 
```
	<gmap-map
			:center="{lat:clinic.latitude, lng:clinic.longtitude}"
			:zoom="16"
			:icon: {path:'http://images.clipartpanda.com/google-map-icon-pin-map-icon-614x460.png'}
			>
			<gmap-marker  :position="{lat:clinic.latitude, lng:clinic.longtitude}"  >

			</gmap-marker>
		</gmap-map>


```

![new map](https://cloud.githubusercontent.com/assets/14367811/26341132/58bfc034-3fa7-11e7-84c9-b607135fb0c2.png)

but don't show my icon
how fix 
please more talk about problem

**Comment by xkjyeah** [comment] 2017-05-24 00:28
Your icon attribute is on the wrong element?

**Comment by davodaslanifakor** [comment] 2017-05-24 05:52
i Cahnge this is to be

`:icon= {path:'http://images.clipartpanda.com/google-map-icon-pin-map-icon-614x460.png'}`

but don't work

**Comment by sayanriju** [comment] 2017-06-06 08:33
@davodaslanifakor  Try changing it to:
`:icon="{url:'http://images.clipartpanda.com/google-map-icon-pin-map-icon-614x460.png'}"`

**Comment by weidadedawei** [comment] 2018-05-15 08:50
><gmap-polyline :path="lineCoordinates" ref="gmapPlRef"
                           :options="{geodesic:true, strokeColor:'#66AA00',strokeWeight:5,icons:gmapIcons}"
                           @path_changed="updatePolylinePath($event)">
            </gmap-polyline>


**data:**

> gmapIcons: [{
                    icon: {
                        path: 'M68.053,32.352c0,0,6.779-24.37-17.906-24.562V7.788c-0.05,0-0.099,0.001-0.148,0.001c-0.048,0-0.096-0.001-0.145-0.001   V7.79C25.167,7.982,31.948,32.352,31.948,32.352s-4.204,0.771-3.219,3.751c0,0,0.852,0.825,4.39-1.063   c0,0-1.118,13.302-0.772,18.517c0,0-1.543,2.102,0.106,4.734l0.426,7.477c0,0-1.012,1.996-1.012,9.418   c0,7-0.236,15.941,16.524,16.936l-0.001,0.092c0.552,0,1.087-0.008,1.609-0.023c0.521,0.016,1.058,0.023,1.609,0.023l-0.001-0.092   c16.759-0.994,16.523-9.936,16.523-16.936c0-7.422-1.011-9.418-1.011-9.418l0.426-7.477c1.648-2.633,0.105-4.734,0.105-4.734   c0.346-5.215-0.771-18.517-0.771-18.517c3.539,1.889,4.391,1.063,4.391,1.063C72.256,33.124,68.053,32.352,68.053,32.352z    M62.324,80.826c0,0-5.341,3.334-12.178,3.334c-6.836,0-12.177-3.334-12.177-3.334V67.984c0,0,4.595,1.312,12.177,1.312   s12.178-1.312,12.178-1.312V80.826z M40.315,52.748v-8.707c0-0.667,0.541-1.207,1.207-1.207h16.956c0.667,0,1.207,0.54,1.207,1.207   v8.707c0,0.666-0.54,1.207-1.207,1.207H41.522C40.856,53.955,40.315,53.414,40.315,52.748z M50.146,38.099   c-8.699,0-13.383,1.941-13.383,1.941L34.955,27.75c0,0,4.471-6.678,15.192-6.678s15.192,6.678,15.192,6.678l-1.81,12.291   C63.529,40.041,58.846,38.099,50.146,38.099z',
                        strokeColor: '#fc1f30',
                        scale: 0.5,
                        strokeWeight: 3,
                        fillOpacity: 1,
                        fillColor: '#f5fbfc',
                        anchor: new google.maps.Point(50, 50)
                    },
                    offset: '0%'
                }],
